language: node_js

sudo: false

node_js:
  - "node"

cache:
  directories:
  - node_modules
  - .vscode-test

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
#   - npm run vscode:prepublish

script:
  - npm run unit_test
  # - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)
