language: node_js
cache:
  directories:
  - node_modules
  - .vscode-test

sudo: false

node_js:
  - "node"

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - xvfb

env:
  - VSCODE_VERSION=stable

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=':99.0';
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm run unit_test
  - npm run integration_test
