name: Converted Workflow
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    Build:
        runs-on: "${{ matrix.os }}"
        strategy:
            matrix:
                include:
                    - os: ubuntu-18.04
                      node-version: 14.x
        steps:
            - name: "Set up Node.js ${{ matrix.node-version }}"
              uses: actions/setup-node@v1
              with:
                  node-version: "${{ matrix.node-version }}"
            - name: Cache multiple paths
              uses: actions/cache@v2
              with:
                  path: |-
                      node_modules
                      .vscode-test
                  key: "${{ runner.os }}-${{ hashFiles('TODO') }}"
            - uses: actions/checkout@v2
            - run: npm install
            - run: "npm run vscode:prepublish"
            - run: npm run unit_test
            - name: Run integration tests
              uses: GabrielBB/xvfb-action@v1
              with:
                  options: -screen 0 1024x768x24
                  run: npm run integration_test
