name: Test autoDocstring
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    unit_tests:
        runs-on: "${{ matrix.os }}"
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      node-version: 14.x
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "${{ matrix.node-version }}"
                  cache: "npm"
            - run: npm install
            - run: npm run vscode:prepublish
            - uses: actions/cache@v2
              with:
                  path: |-
                      node_modules
                      .vscode-test
                  key: "${{ runner.os }}-${{ hashFiles('TODO') }}"
            - run: npm run unit_test

    integration_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "${{ matrix.node-version }}"
                  cache: "npm"
            - uses: GabrielBB/xvfb-action@v1
              with:
                  options: -screen 0 1024x768x24
                  run: npm run integration_test
