name: Test autoDocstring
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    unit_tests:
        runs-on: "${{ matrix.os }}"
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node: [14]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "${{ matrix.node-version }}"
                  cache: "npm"
            - run: npm install
            - run: npm run vscode:prepublish
            - run: npm run unit_test

    integration_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: "npm"
            - run: npm install
            - run: npm run prepare_integration_tests
            - uses: GabrielBB/xvfb-action@v1
              with:
                  options: -screen 0 1024x768x24
                  run: npm run integration_test
